spring.application.name=notificacao-service
server.port=8080

# Endereço do cluster KRaft no WSL 2
spring.kafka.bootstrap-servers=localhost:9092

# Configuração do Consumidor
spring.kafka.consumer.group-id=grupo-seminario
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Permite que o Spring confie em qualquer pacote de classes para converter o JSON
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.notificacao_service.PedidoRecord